-- Agrega una columna id identity y la deja como primary key en public.intercambios.
-- Ejecutar en el SQL Editor de Supabase.

BEGIN;

-- 1) Agregar la columna si no existe
ALTER TABLE public.intercambios
ADD COLUMN IF NOT EXISTS id BIGINT;

-- 2) Rellenar filas existentes que todavía no tengan id
WITH filas AS (
  SELECT ctid, ROW_NUMBER() OVER (ORDER BY ctid) AS nuevo_id
  FROM public.intercambios
  WHERE id IS NULL
)
UPDATE public.intercambios i
SET id = filas.nuevo_id
FROM filas
WHERE i.ctid = filas.ctid;

-- 3) Dejar la columna como NOT NULL antes de agregar identity
ALTER TABLE public.intercambios
ALTER COLUMN id SET NOT NULL;

-- 4) Convertirla a identity si ya existía como serial/default normal
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'intercambios'
      AND column_name = 'id'
      AND is_identity = 'YES'
  ) THEN
    ALTER TABLE public.intercambios ALTER COLUMN id DROP DEFAULT;
    ALTER TABLE public.intercambios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- 5) Asegurar que la secuencia siga después del último id
DO $$
DECLARE
  max_id BIGINT;
  seq_name TEXT;
BEGIN
  SELECT COALESCE(MAX(id), 0) INTO max_id
  FROM public.intercambios;

  SELECT pg_get_serial_sequence('public.intercambios', 'id') INTO seq_name;

  IF seq_name IS NOT NULL THEN
    IF max_id > 0 THEN
      PERFORM setval(seq_name, max_id, true);
    ELSE
      PERFORM setval(seq_name, 1, false);
    END IF;
  END IF;
END $$;

-- 6) Agregar la primary key si la tabla no tiene una
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.intercambios'::regclass
      AND contype = 'p'
  ) THEN
    ALTER TABLE public.intercambios
    ADD CONSTRAINT intercambios_pkey PRIMARY KEY (id);
  END IF;
END $$;

COMMIT;
